# ----------------------------------------
# GENERIC CORE PROPERTIES
# PROFILE SPECIFIC IN DEV , QA AND PROD APPLICATION-{PROFILE}.YML FILES 
# ----------------------------------------


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
#LOGGING
logging:
  file: logs/application.log

server:
  port: 10001

# ZUUL CONFIG
#-------------------------------   
zuul:
  prefix: /API
  routes:  
    customer-management-service:
       path: /CUSTOMER-MANAGEMENT/V1.0/**
       service-id: customer-management-service
    account-management-service:
       path: /**
       service-id: account-management-service
    customer-account-management-service:
       path: /CUSTOMER-ACCOUNT-COMPOSITE/V1.0/**
       service-id: customer-account-management-service
       
       
                  
# CLOUD CONFIG
#-------------------------------  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
    

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
info:
  component: Zuul Gateway Service App
  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,health,metrics,env,httptrace,configprops
  server:
    servlet:
      context-path: /
  endpoint:
    configprops:
      enabled: true
    httptrace:
      enabled: true
    env:
      enabled: true
    threaddump:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true
    