FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/Account-Management-1.0.jar Account-Management-1.0.jar
ENTRYPOINT exec java -jar /Account-Management-1.0.jar account-management-service
EXPOSE 12001