FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/Account-Management-1.0.jar Account-Management-1.0.jar
ENTRYPOINT ["java", "-jar", "/Account-Management-1.0.jar"]
EXPOSE 12001