FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/Customer-Account-Management-1.0.jar Customer-Account-Management-1.0.jar
ENTRYPOINT ["java", "-jar", "/Customer-Account-Management-1.0.jar"]
EXPOSE 13001