FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/ConfigService-1.0.jar ConfigService-1.0.jar
ENTRYPOINT exec java -jar /ConfigService-1.0.jar Cloud-Config-Service
EXPOSE 8001