spring:
  application:
    name: ${springboot.app.name:AdminService}

server:
  port: 8002


eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
    healthcheck:
      enabled: true

# Configure Spring Boot Admin
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF