spring:
  application:
    name: ${springboot.app.name:AdminService}

server:
  port: 8002


eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
    healthcheck:
      enabled: true

# Configure Spring Boot Admin
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream


# Configure Slack Notification
spring.boot.admin.notify.slack.enabled: true
spring.boot.admin.notify.slack.ignore-changes: "UNKNOWN:TEST" #By Default admin ignores changes "UNKNOWN:UP"
spring.boot.admin.notify.slack.webhook-url: https://hooks.slack.com/services/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
spring.boot.admin.notify.slack.message: "*#{instance.registration.name}* (#{instance.id}) is *#{event.statusInfo.status}*"


# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF