
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
# EMBEDDED SERVER CONFIGURATION
server:
  port: 13001
  
  
  
# CLOUD CONFIG
#-------------------------------  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
  
  
  