FROM openjdk
MAINTAINER Dipankar Chatterjee <dipankar.c@hcl.com>
ADD target/HystrixDashboardService-1.0.jar HystrixDashboardService-1.0.jar
ENTRYPOINT exec java -jar /HystrixDashboardService-1.0.jar HystrixDashboardService
EXPOSE 9090
