# CLOUD CONFIG
#-------------------------------  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
      
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
    

server:
   port: 8001
   
#-----------------------------------------
# GITHUB Config file location with Enviornments
#-----------------------------------------
spring:  
  cloud:
    config:
      uri: http://localhost:8001
      server:
        git:
          uri: https://github.com/dipsscor/CustomerPortalSampleApplication-Repos
          skipSslValidation: true
          repos:
            DEV:
              pattern: 
                - '*/DEV'
                - '*/QA'
              uri: https://github.com/dipsscor/CustomerPortalSampleApplication-Repos/DEV
            QA:
              pattern: 
                - '*/QA'
              uri: https://github.com/dipsscor/CustomerPortalSampleApplication-Repos/QA
            PROD:
              pattern: 
                - '*/PROD'
              uri: https://github.com/dipsscor/CustomerPortalSampleApplication-Repos/PROD
            LOCAL:
              pattern:
                - '*/LOCAL'
              uri: https://github.com/dipsscor/CustomerPortalSampleApplication-Repos/DEV