# ----------------------------------------
# GENERIC CORE PROPERTIES
# PROFILE SPECIFIC IN DEV , QA AND PROD APPLICATION-{PROFILE}.YML FILES 
# ----------------------------------------


# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
#LOGGING
logging:
  file: logs/application.log
    
    

    
#-----------------------------------------
# PROFILES
#-----------------------------------------
spring:
  profiles:
    active:
      - PROD
        


# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
info:
  component: Cloud Config Service App
  
management:
  endpoints:
    enabled-by-default: true
  server:
    servlet:
      context-path: /
  endpoint:
    threaddump:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true
