# CLOUD CONFIG
#-------------------------------  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:9001}/eureka/
      
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
    

server:
   port: 8001
   
#-----------------------------------------
# GITHUB Config file location
#-----------------------------------------
spring:  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dipsscor/Cloud-Config-Service